// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/get-cabin-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_cabin_info_default = defineTool({
  name: "get_cabin_info",
  title: "Get cabin info",
  description: "Returns key facts about the Norrskensstigen cabin: location, capacity, sleeping arrangements, ski access, and amenities.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Norrskensstigen",
      location: "St\xF6ten, Granfj\xE4llsbyn, Sweden",
      style: "Nordic mountain log cabin",
      skiAccess: "Ski-in/Ski-out",
      beds: 12,
      amenities: [
        "Sauna",
        "Mountain view",
        "Fully equipped kitchen",
        "Fireplace",
        "Free parking"
      ],
      website: "https://norrskensstigen.lovable.app",
      languages: ["Swedish", "English", "German"]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/get-winter-pricing.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var winterPricing = [
  { week: 50, dates: "5/12 - 12/12 2026", priceSek: 6500, status: "Available", note: "Grand opening" },
  { week: 51, dates: "12/12 - 19/12 2026", priceSek: 9e3, status: "Available" },
  { week: 52, dates: "19/12 - 26/12 2026", priceSek: 27500, status: "Available", note: "Julveckan (Christmas week)" },
  { week: 53, dates: "26/12 2026 - 2/1 2027", priceSek: 29e3, status: "Available", note: "Ny\xE5rsveckan (New Year week)" },
  { week: 1, dates: "2/1 - 9/1 2027", priceSek: 15e3, status: "Booked" },
  { week: 2, dates: "9/1 - 16/1 2027", priceSek: 11e3, status: "Booked" },
  { week: 3, dates: "16/1 - 23/1 2027", priceSek: 11e3, status: "Booked" },
  { week: 4, dates: "23/1 - 30/1 2027", priceSek: 15500, status: "Available" },
  { week: 5, dates: "30/1 - 6/2 2027", priceSek: 17500, status: "Booked" },
  { week: 6, dates: "6/2 - 13/2 2027", priceSek: 19500, status: "Booked" },
  { week: 7, dates: "13/2 - 20/2 2027", priceSek: 28e3, status: "Available", note: "Sportlov" },
  { week: 8, dates: "20/2 - 27/2 2027", priceSek: 28e3, status: "Available", note: "Sportlov" },
  { week: 9, dates: "27/2 - 6/3 2027", priceSek: 28e3, status: "Available", note: "Sportlov" },
  { week: 10, dates: "6/3 - 13/3 2027", priceSek: 21e3, status: "Available", note: "Sportlov" },
  { week: 11, dates: "13/3 - 20/3 2027", priceSek: 19500, status: "Booked" },
  { week: 12, dates: "20/3 - 27/3 2027", priceSek: 23500, status: "Available", note: "P\xE5sk (Easter)" },
  { week: 13, dates: "27/3 - 3/4 2027", priceSek: 23500, status: "Available", note: "P\xE5sk (Easter)" },
  { week: 14, dates: "3/4 - 11/4 2027", priceSek: 14e3, status: "Available" }
];
var get_winter_pricing_default = defineTool2({
  name: "get_winter_pricing",
  title: "Get winter pricing and availability",
  description: "Returns the full winter season 2026/2027 pricing table with week number, dates, price in SEK, and booking status (Saturday-to-Saturday, 7-night stays). Optionally filter by status.",
  inputSchema: {
    status: z.enum(["Available", "Booked", "All"]).optional().describe("Filter to only available, only booked, or all weeks. Defaults to All.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status }) => {
    const filtered = !status || status === "All" ? winterPricing : winterPricing.filter((w) => w.status === status);
    const payload = {
      season: "Winter 2026/2027",
      currency: "SEK",
      stayRule: "Saturday to Saturday, 7 nights",
      cleaningIncluded: true,
      weeks: filtered
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-summer-pricing.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_summer_pricing_default = defineTool3({
  name: "get_summer_pricing",
  title: "Get spring/summer/autumn pricing",
  description: "Returns pricing for the non-winter season (spring, summer, autumn) at Norrskensstigen.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = {
      season: "Spring, Summer & Autumn",
      currency: "SEK",
      cleaningIncluded: true,
      rates: [
        { unit: "Week (7 nights)", priceSek: 5500 },
        { unit: "Long weekend (3 nights)", priceSek: 4e3 }
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Returns contact information for booking inquiries at Norrskensstigen.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = {
      email: "info@norrskensstigen.se",
      phone: "+46 705 85 58 55",
      website: "https://norrskensstigen.lovable.app",
      contactPage: "https://norrskensstigen.lovable.app/#contact",
      responseTime: "Within 24 hours"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "norrskensstigen-mcp",
  title: "Norrskensstigen MCP",
  version: "0.1.0",
  instructions: "Public tools for the Norrskensstigen mountain cabin in St\xF6ten, Granfj\xE4llsbyn. Use these to look up cabin facts, winter 2026/2027 pricing and availability by week, spring/summer/autumn pricing, and contact details for booking inquiries.",
  tools: [get_cabin_info_default, get_winter_pricing_default, get_summer_pricing_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
